### ISSUE TITLE
Unable to use because of ZonedDateTime

### ISSUE THREAD

**Issue by yogikorke** [ta4j/ta4j#184] opened 2018-02-17 11:32 UTC
Hi I want to use this library for Android App. But this library uses ZonedDateTime class which is supported only in Oreo (API 26) based Android devices. You can confirm it from below URL : https://developer.android.com/reference/java/time/ZonedDateTime.html
So my question is how I can use this library function for older API based devices. Oreo is not available on almost 80% of total Android devices as of now.

**Comment by edlins** [comment] 2018-02-17 20:53
This appears to be true.  Should probably update the README to state the minimum Android API level, or to state that Android is not supported.  Did you find any other examples of high API level requirements, so we can document?  That would be helpful.

**Comment by team172011** [comment] 2018-02-18 12:53
It might have been worth considering wether we need the `ZonedDateTime ` field in each bar. A simple timestamp would also be sufficient or not?

**Comment by yogikorke** [comment] 2018-02-18 13:48
Yes. A simple timestamp also will be sufficient. In previous version of Ta4j jodatime was used for datetime format. It will be fine if you use jodatime in latest version of library.

**Comment by yogikorke** [comment] 2018-02-24 19:49
Agree.
But there should be some alternative like jodatime, java date time for
those who want to use this library in Android platform. Earlier version of
this library had joda time specifications. Newer versions of library can
have both timezone and joda time options. Developer will use one of it as
per his requirement.

**Comment by team172011** [comment] 2018-02-25 09:26
@yogikorke so you cannot use ta4j on api < 26 at all? What exception do you get (NoClassDef?)? It will take some time to find and implement a appropriate solution. But there are not many usages of ZonedDateTime and you could replace it manually for a workaround

**Comment by team172011** [comment] 2018-02-25 09:54
@abzif also agree,
but should handling of time zones be challenged by this lib? Internally there is no need to have a time zone for the calculations in ta4j

**Comment by yogikorke** [comment] 2018-02-25 12:57
@team172011 If I use this library for API < 26 it throws exception ClassNotFoundException as this ZonedDateTime class was added in API 26 (Oreo). So it will work only on Oreo devices which is latest version of Android and almost 80% of users dont have it as Oreo update is not rolled out for older devices by many manufacturers.

**Comment by abzif** [comment] 2018-02-26 10:07
@team172011 Maybe the creators of ta4j had some reason to use ZonedDateTime. However, for now I can't see any reason behind it. In my opinion using of LocalDateTime would be enough.

**Comment by team172011** [comment] 2018-02-26 14:47
@abzif I think the only reason was to minimize third party dependencies.

**Comment by mdeverdelhan** [comment] 2018-02-26 15:39
> Maybe the creators of ta4j had some reason to use ZonedDateTime.

Because of the following statement ([on Joda's site](http://www.joda.org/joda-time/index.html#Why_Joda_Time)): __Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.__

Then, when using java.time, ZonedDateTime is usually preferred to LocalDateTime.

**Comment by jcuypers** [comment] 2018-03-10 15:03
I can confirm the issue.  Min api ver is 26 for ZonedDateTime as well as Duration on Android.  When switching min.sdk basic examples on 0.12-develop seem to work.  I have found the following resource that might help someone to figure out a way to work around this:  [backport](http://www.threeten.org/threetenbp/)
thanks

**Comment by yogikorke** [comment] 2018-03-10 16:34
So in short you mean I can use ZonedDateTime class from this backport
library for Android APIs < 26 without any problem.
I will try this soon.
Thanks.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jcuypers** [comment] 2018-03-10 21:26
@yogikorke.  I've managed to get a simple example working (0.12-develop with a simple timeseries and rsi/macd/ema calculation) on API 23.  The backport uses another namespace, so I compiled the library again after changing  the names and then I was able to use it.  Hope there's a way to nicely/easily make it work for everyone in 0.13

**Comment by jcuypers** [comment] 2018-03-10 22:29
The new minimum without further modification if API 24 as it required for the streams.

**Comment by yogikorke** [comment] 2018-03-11 07:56
Hey @jcuypers please go through this code:
```

import org.threeten.bp.LocalDate;
import org.threeten.bp.format.DateTimeFormatter;
import org.threeten.bp.ZonedDateTime;
import org.threeten.bp.ZoneId;

private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"); 
List<Bar> bars = new ArrayList<>();
    String date_time = myList.get(i).getT();
    ZonedDateTime date = LocalDate.parse(date_time, 
    DATE_FORMAT).atStartOfDay(ZoneId.systemDefault());
 
// But this BaseBar constructor takes "java.time.ZonedDateTime" type of date parameter so it shows cannot resolve "org.threeten.bp.ZonedDateTime" type of date object. How to resolve this? Is there way to typecast this object to threeten.bp object to java.time object? 
bars.add(new BaseBar(**date**, open, high, low, close, volume));
```
I am new to android developement and java. Any help appreciated in advance.

**Comment by jcuypers** [comment] 2018-03-11 08:31
@yogikorke I'm a beginner myself, but I'll do my best.    The real clue is to not only use the threeten backport into your own code but also to replace/use it in the ta4j library and recompile it (all java.time.* imports need to be recplaced by org.threeten.bp.*)  You cannot just cast it to the right type.

Then when using it, i had to make some minor changes:

```
// Everything based on java.time.*

BaseTimeSeries.SeriesBuilder timeSeriesBuilder = new BaseTimeSeries.SeriesBuilder();
TimeSeries seriesB = timeSeriesBuilder.withName("Series").withNumTypeOf(BigDecimalNum::valueOf).build();

for (**loop over some data**) {
  LocalDateTime ldt = LocalDateTime.ofInstant(Instant.ofEpochSecond(c.time), TimeZone.getDefault().toZoneId());
 ZonedDateTime zdt = ZonedDateTime.of(ldt, TimeZone.getDefault().toZoneId());

 seriesB.addBar(zdt, c.open, c.high, c.low, c.close, c.volumefrom);

}
ClosePriceIndicator closePriceIndicator = new ClosePriceIndicator(seriesB);
RSIIndicator rsi = new RSIIndicator(closePriceIndicator,100);
MACDIndicator macdIndicator = new MACDIndicator(rsi);
EMAIndicator ema = new EMAIndicator(rsi,12);

 for (int i=0; i<seriesB.getBarCount(); i++) {
                        Timber.i("Close : "+closePriceIndicator.getValue(i)+"  RSI: "+rsi.getValue(i));
}

```


```
// with threeten (same as above but minor changes)
 LocalDateTime ldt = LocalDateTime.ofInstant(Instant.ofEpochSecond(c.time), systemDefault());
 ZonedDateTime zdt = ZonedDateTime.of(ldt, systemDefault());
```

**Comment by team172011** [comment] 2018-03-11 11:45
@yogikorke like @jcuypers descriped, you have to change the code in this lib. That means you cannot add it as maven dependency, but have to clone or download this repository and replace the `java.time.*` imports with the corresponding backport imports. By the way, if you have to modify the code of this repository for your own usage, you can also replace `java.time` code with simple timestamps or similar without using another dependency like threetenbp. It depens on your case of application

**Comment by jcuypers** [comment] 2018-03-11 12:20
@team172011 I think its good to get an agreement on how things can evolve for the future. My knowledge is too limited to see all the possibilities or limitations of any approach.  Currently I've got it running on API 23
So the main issues are the date / time which locks it to API 26  and then next thing is the recently added num (which uses java.util.function.Function) which locks it to API 24.  Do you know of an easy way to integrate this in a specific platform code into the current project or create a side project that can easily take in new updates from the existing project.

**Comment by edlins** [comment] 2018-03-12 17:54
There is a [`Function`](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/Function.html) `Interface` in `Guava` but I've never used `Guava`.
https://github.com/google/guava/wiki/Compatibility

**Comment by jcuypers** [comment] 2018-03-12 18:20
Thanks, I guess it will work with Guava too.  I used the [streamsupport](https://github.com/streamsupport/streamsupport) library and can confirm it works.  Getting it to work one time is one thing,  being able to integrate easily all new developments is another.   For now I'm ok, i just needed some indicators.  would be nice if it could work out of the box.

**Comment by edlins** [comment] 2018-03-13 17:52
I agree it would be nice to provide easier Android compatibility.  If you'd like to push your branch to a forked repo I'd like to look over the changes.

**Comment by jcuypers** [comment] 2018-03-13 19:21
I have no problem with sharing, but in essence I've only changed standard libraries with backports (import statements).  The tricky part is that I have made my own setup now, and it will be difficult to merge back. 
since the direct git import was giving me a hard time, I've downloaded the zip files and imported it into a freshly created gradle/android studio project and worked from there.   If you like I can upload as a seperate project on my account and you can still see if its useful

**Comment by jcuypers** [comment] 2018-03-13 20:09
you can have a quick look here [link](https://github.com/jcuypers/Ta4j-android/tree/master/ta4jjcuypers/Ta4j-android)

**Comment by edlins** [comment] 2018-03-13 20:48
Okay, you created a new repository rather than forking ta4j/ta4j so I can't compare your branch to ta4j's branch automatically on github.  That makes it more difficult to assess the specific code changes.  I might try to clone it to do a manual `git diff` but I can't do that today.

**Comment by jcuypers** [comment] 2018-03-14 18:10
yes sorry. bcs of the explained issued.  just check the import statements and the libraries added to the projects.  these are the only changes.  I compile it to an aar and add it to another project for use

**Comment by team172011** [comment] 2018-03-14 19:07
@jcuypers it is also managed by gradle and you have removed the maven framework. Would you contribute your changes to a new ta4j branch? I could push a new develop checkout, merge your PR and create a tag 0.12-andriod_25 within the next release

**Comment by jcuypers** [comment] 2018-03-14 20:37
I can try but for some reason the whole import and push didnt work directly
with android studio.  I'll see what i can do to help.   Can we both
maintain maven and gradle in the seperate branch?

**Comment by team172011** [comment] 2018-03-14 21:43
I think for android we only need gradle

**Comment by jcuypers** [comment] 2018-03-15 09:25
Ok I'll give it a try.

**Comment by yogikorke** [comment] 2018-03-21 07:29
@jcuypers 
I checked ur modified version of ta4j with threebackten library.
I have doubt.

1.What is last parameter I need to pass while defining constructor for BaseBar:
 
BaseBar(ZonedDateTime endTime, double openPrice, double highPrice, double lowPrice, double closePrice, double volume, Function<Number, Num> numFunction).

2. what are java8 imports. I am getting cannot resolve java8 error.

Can you please explain these two lines with example.

**Comment by jcuypers** [comment] 2018-03-21 08:12
@yogikorke 
As of v0.12-develop there is a notion of a NUM type which makes ta4j "agnostic" of the real data type used. You can just define the actual type on the dataseries as per your need (for example DoubleNum is 6x faster than BigDecimalNum on a test phone):

BaseTimeSeries.SeriesBuilder timeSeriesBuilder = new BaseTimeSeries.SeriesBuilder();
TimeSeries seriesB = timeSeriesBuilder.withName("Series").withNumTypeOf(**BigDecimalNum**::valueOf).build();

Point 1: the function just makes the conversion between a certain type and the Num type (just use the builder on the series which is the easiest)

Point 2:  the above functionality is created / available through java1.8 spec  function java.util.function.  Obviously as with the Zoned data time this is only available from API.   this is why we need another backport which uses the name naming so this is why there needs to be a different namespace  java8.util.Function instead of java.util.Function.   In order to have this work I used the streamsupport backport. please look at the gradle files what is needed.

According to me, if you would stay on 0.11 and only change the datetime issue it would work and theres no need for the NUM changes.  For me it compiles fine and works as expected with the indicators.

Anyway, when they get to publishing the newer version i will  try to merge under a different branch and i guess things will be easier.

GL
J.

**Comment by jcuypers** [comment] 2018-03-21 08:20
Ok, just let me know than when I need to push.   I hope you can assist if
needed.

2018-03-14 23:43 GMT+02:00 Simon W, <notifications@github.com>:

**Comment by yogikorke** [comment] 2018-03-21 10:48
Thanks @jcuypers . I replaced java.time with threetenbackport in ta4j library source code(0.11). Now its working nicely on my Android Device (API <26). Thank you so much.

**Comment by jcuypers** [comment] 2018-03-22 08:34
@team172011 I've downloaded the 0.12 android branch.  converted it into gradle setup. then changed the core library with my initial changes. which compiles fine.  tried to run the examples (which i never used before).  seems to be one issue with instant to date conversion.  solved this with a helper function. compiles fine after that.  When I run it.  It complains of not finding the time data for the android threethen port.  As I used it in a real android project for me this is a non issue.  as i just run the init and done:   I would like to have some guidance on how far we can make this version different than the original.   In order to make it nicer i guess is to make the examples android specific

**Comment by team172011** [comment] 2018-05-17 16:34
Pleas take a look at https://github.com/ta4j/ta4j/tree/0.12-android, I have pushed some changed that make this branch java6 compatible (test adjusted not jet)

**Comment by andersonbadari** [comment] 2018-05-27 19:03
@team172011 Jitpack.io can't compile this. See this log: https://jitpack.io/com/github/ta4j/ta4j/0.12-android-0.12-SNAPSHOT-gc75a94e-46/build.log

**Comment by rohit00082002** [comment] 2019-02-14 04:59
Hello everyone, I am new to android, I need to use this library for Android Min SDK version 22, please tell me step by step how to use/import this 12-android library to my this project? I tried and get Java8 error, I am not using java8 and also ZonedDateTime can not use.

**Comment by yogikorke** [comment] 2019-02-14 05:08
Check this : https://www.threeten.org/threetenbp/

**Comment by rohit00082002** [comment] 2019-02-14 05:15
Yes that I understood to import this library is needed. but I tried so much of ta4j, ta4j-android, snapshot that it all mashed up, I need to use ta4j android for api 22, so what should I put in grade file? Or if not from gradle then should I download zip from https://github.com/ta4j/ta4j/tree/0.12-android ? then after that how to use it?

**Comment by rohit00082002** [comment] 2019-02-14 06:15
I manually download this 0.12-android repo and added into project as module dependency, it showing this error

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :ta4j-0.12-android.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :ta4j-0.12-android.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :ta4j-0.12-android.
Show Details
Affected Modules: app

**Comment by yogikorke** [comment] 2019-02-14 06:55
Download normal TA4J library for java. Use threeten backport library for
importing Java 8 related stuff.

**Comment by rohit00082002** [comment] 2019-02-14 07:52
//implementation 'com.jakewharton.threetenabp:threetenabp:1.0.5'
    implementation 'org.threeten:threetenbp:1.3.8'
    //implementation 'org.ta4j:ta4j-core:0.12'
    //implementation 'org.ta4j:ta4j-examples:0.12'
    //implementation 'org.ta4j-android:ta4j-core:0.12'
    //implementation project(path: ':ta4j-0.12-android')
    //implementation project(path: ':ta4j0212android')
    implementation 'org.ta4j:ta4j-core:0.12'

I tried both threetenabp , previously when I started trying to get ta4j in my project then this normal ta4j-core and ta4j-example was able to import and then in using function I was getting java8 error,

BUT NOW, even build is failing 

> Task :app:mergeExtDexDebug FAILED
AGPBI: {"kind":"error","text":"Default interface methods are only supported starting with Android N (--min-api 24): org.ta4j.core.Strategy org.ta4j.core.AnalysisCriterion.chooseBest(org.ta4j.core.TimeSeriesManager, java.util.List)","sources":[{}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Failed to transform file 'ta4j-core-0.12.jar' to match attributes {artifactType=android-dex, dexing-is-debuggable=true, dexing-min-sdk=22} using transform DexingTransform
   > Error while dexing.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1054)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:123)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1028)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:76)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$FileCollectionVisitorImpl.visitCollection(DefaultFileSystemSnapshotter.java:257)
	at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:282)
	at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:206)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.snapshot(DefaultFileSystemSnapshotter.java:142)
	at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:54)
	at org.gradle.internal.fingerprint.impl.AbstractPathOnlyFileCollectionFingerprinter.fingerprint(AbstractPathOnlyFileCollectionFingerprinter.java:37)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.fingerprintTaskFiles(CacheBackedTaskHistoryRepository.java:358)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.createExecution(CacheBackedTaskHistoryRepository.java:163)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.access$100(CacheBackedTaskHistoryRepository.java:76)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1.getCurrentExecution(CacheBackedTaskHistoryRepository.java:123)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:200)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:94)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:50)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.artifacts.transform.ArtifactTransformException: Failed to transform file 'ta4j-core-0.12.jar' to match attributes {artifactType=android-dex, dexing-is-debuggable=true, dexing-min-sdk=22} using transform DexingTransform
	at org.gradle.api.internal.artifacts.transform.UserCodeBackedTransformer.transform(UserCodeBackedTransformer.java:90)
	at org.gradle.api.internal.artifacts.transform.ChainedTransformer.transform(ChainedTransformer.java:39)
	at org.gradle.api.internal.artifacts.transform.TransformArtifactOperation.run(TransformArtifactOperation.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.access$900(DefaultBuildOperationExecutor.java:48)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$ParentPreservingQueueWorker.execute(DefaultBuildOperationExecutor.java:342)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:230)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.access$600(DefaultBuildOperationQueue.java:172)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:203)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:203)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:177)
	at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForCompletion(DefaultBuildOperationQueue.java:116)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:137)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.runAll(DefaultBuildOperationExecutor.java:110)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.runAll(DelegatingBuildOperationExecutor.java:41)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ParallelResolveArtifactSet$VisitingSet.visit(ParallelResolveArtifactSet.java:60)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.visitArtifacts(DefaultLenientConfiguration.java:256)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.access$500(DefaultLenientConfiguration.java:69)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$2.run(DefaultLenientConfiguration.java:231)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.visitArtifactsWithBuildOperation(DefaultLenientConfiguration.java:228)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.access$200(DefaultLenientConfiguration.java:69)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$1.visitArtifacts(DefaultLenientConfiguration.java:133)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1025)
	... 42 more
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
	at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
	at com.android.build.gradle.internal.dependency.DexingTransform.transform(DexingTransform.kt:56)
	at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:44)
	at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:29)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:251)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:238)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:91)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:87)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.doAdd(DefaultPathKeyFileStore.java:137)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.doAdd(DefaultPathKeyFileStore.java:127)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:87)
	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:50)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:163)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:142)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:90)
	at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:193)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:170)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:195)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:142)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:135)
	at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.loadIntoCache(DefaultTransformedFileCache.java:135)
	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.getResult(DefaultTransformedFileCache.java:127)
	at org.gradle.api.internal.artifacts.transform.UserCodeBackedTransformer.transform(UserCodeBackedTransformer.java:88)
	... 73 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:70)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
	at com.android.tools.r8.D8.run(D8.java:94)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
	... 96 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Default interface methods are only supported starting with Android N (--min-api 24): org.ta4j.core.Strategy org.ta4j.core.AnalysisCriterion.chooseBest(org.ta4j.core.TimeSeriesManager, java.util.List)
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:89)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:60)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:64)
	... 99 more

**Comment by yogikorke** [comment] 2019-02-14 11:20
Try older version of ta4j.

**Comment by team172011** [comment] 2019-09-07 10:36
I will close this ticket. For the time being there is no capacity for a direct < android 8 supporting library

**Closed by team172011** 2019-09-07 10:36 UTC
Labels: enhancement, question

**Comment by mtn1988** [comment] 2020-05-16 13:50
Android Studio 4.0 has solved this issue!!
https://developer.android.com/studio/preview/features#j8-desugar
