### ISSUE TITLE
Use Instant instead of ZonedDateTime as core time implementation

### ISSUE THREAD

**Issue by sgflt** [ta4j/ta4j#1188] opened 2024-10-03 08:00 UTC
**I have checked existing issues and wiki**
- [x] I could not find similar [issues](https://github.com/ta4j/ta4j/issues?utf8=%E2%9C%93&q=)
- [x] I could not find a solution in the [wiki](https://ta4j.github.io/ta4j-wiki/) or [faq section](https://ta4j.github.io/ta4j-wiki/FAQ.html)

**Is your feature request related to a problem? Please describe.**

1. Zoned time variant has problem with DST.
2. Brokers publish time as milliseconds from 1.1.1970 which is obviously Instant.
3. Instant is core, *Date classes are better suitable for time presentation 

**Describe the solution you'd like**
Migrate *Date apis to Instant

**Comment by TheCookieLab** [comment] 2024-10-09 12:37
No, we will not be replacing ZonedDateTime with Instant. This would remove time zone functionality that many - including myself - rely on and offers nothing to replace it. 

I don't view charts in UTC and when I look at price data, I want to see them in my local time. The broker's published time format is irrelevant; we don't need to be 1:1 because Bar is Ta4j's _canonical_ representation of the data. We represent timestamps in the format _we_ want to seem them in, and for anyone that actually looks at the timestamps that's with time zone included. 

Not having timestamps in the format end-users care about and have built around is both a strict loss in functionality and a breaking API change. For this class of change there is a very high bar to clear, and the provided rationale is unconvincing. What problem does ZonedDateTime have with DST? I've not run into anything that's affected my work. Regardless if there's a bug, the correct solution is to wait for the official fix, not to abandon ZonedDateTime (and DST support) altogether. That's akin to solving New York City's rat problem by nuking NYC.

The only argument that would make this change compelling is if switching from ZonedDateTime to Instant significantly improves performance when working with Bars, BarSeries, etc. If the performance increases were large enough then I would be willing to entertain the trade-off of losing time zone information (pushing the conversion down the user's client code if/when they want to see timestamps in their local time). For this I would need to see a performance analysis (timing, memory usage) between the the approaches for common use cases (creating barseries, running strategies, etc). Similar to what was done for #956 .

**Comment by sgflt** [comment] 2024-10-09 17:32
```
jshell> DSTProblems.main(null);
DST Gap Problem (Spring Forward):
When clock moves forward from 2AM to 3AM, one hour of time doesn't exist
Attempted time: 2024-03-10T02:30
Actual time:    2024-03-10T03:30-04:00[America/New_York]
Notice how 2:30 AM was automatically moved to 3:30 AM!

==================================================

DST Overlap Problem (Fall Back):
When clock moves back from 2AM to 1AM, one hour occurs twice
Same local time occurs twice:
First occurrence:  2024-11-03T01:30-04:00[America/New_York]
Second occurrence: 2024-11-03T01:30-05:00[America/New_York]
Local time for both: 2024-11-03T01:30

==================================================

OHLC Data Problems During DST:
Created candle: 2024-03-10 01:00 EST - O:100,0 H:105,0 L:95,0 C:102,0
Created candle: 2024-03-10 03:00 EDT - O:101,0 H:106,0 L:96,0 C:103,0
Created candle: 2024-03-10 03:00 EDT - O:102,0 H:107,0 L:97,0 C:104,0
Created candle: 2024-03-10 04:00 EDT - O:103,0 H:108,0 L:98,0 C:105,0

Time differences between consecutive candles:
Between candle 1 and 2: 60 minutes
Between candle 2 and 3: 0 minutes
Between candle 3 and 4: 60 minutes

```

```java
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public class DSTProblems {
    public static void main(String[] args) {
        // Demonstrate DST problems in US Eastern Time
        demonstrateDSTGap();
        System.out.println("\n" + "=".repeat(50) + "\n");
        demonstrateDSTOverlap();
        System.out.println("\n" + "=".repeat(50) + "\n");
        demonstrateOHLCProblem();
    }

    private static void demonstrateDSTGap() {
        System.out.println("DST Gap Problem (Spring Forward):");
        System.out.println("When clock moves forward from 2AM to 3AM, one hour of time doesn't exist");
        
        ZoneId zoneId = ZoneId.of("America/New_York");
        
        // March 10, 2024 2:30 AM - This time doesn't exist due to DST!
        LocalDateTime problemTime = LocalDateTime.of(2024, 3, 10, 2, 30);
        
        try {
            ZonedDateTime zdt = ZonedDateTime.of(problemTime, zoneId);
            System.out.println("Attempted time: " + problemTime);
            System.out.println("Actual time:    " + zdt);
            // Java will automatically adjust to 3:30 AM
            System.out.println("Notice how 2:30 AM was automatically moved to 3:30 AM!");
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    private static void demonstrateDSTOverlap() {
        System.out.println("DST Overlap Problem (Fall Back):");
        System.out.println("When clock moves back from 2AM to 1AM, one hour occurs twice");
        
        ZoneId zoneId = ZoneId.of("America/New_York");
        
        // November 3, 2024 1:30 AM - This time occurs twice!
        LocalDateTime ambiguousTime = LocalDateTime.of(2024, 11, 3, 1, 30);
        
        ZonedDateTime firstOccurrence = ZonedDateTime.of(ambiguousTime, zoneId);
        ZonedDateTime secondOccurrence = firstOccurrence.plusHours(1);
        
        System.out.println("Same local time occurs twice:");
        System.out.println("First occurrence:  " + firstOccurrence);
        System.out.println("Second occurrence: " + secondOccurrence);
        System.out.println("Local time for both: " + ambiguousTime);
    }

    private static void demonstrateOHLCProblem() {
        System.out.println("OHLC Data Problems During DST:");
        
        ZoneId zoneId = ZoneId.of("America/New_York");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        
        // Create hourly OHLC data around DST spring forward
        List<OHLC> ohlcData = new ArrayList<>();
        
        LocalDateTime startTime = LocalDateTime.of(2024, 3, 10, 1, 0);
        
        // Try to create 4 hourly candles
        for (int i = 0; i < 4; i++) {
            LocalDateTime candleTime = startTime.plusHours(i);
            try {
                ZonedDateTime zdt = ZonedDateTime.of(candleTime, zoneId);
                OHLC candle = new OHLC(zdt, 100 + i, 105 + i, 95 + i, 102 + i);
                ohlcData.add(candle);
                System.out.println("Created candle: " + candle);
            } catch (Exception e) {
                System.out.println("Failed to create candle for " + 
                    candleTime.format(formatter) + ": " + e.getMessage());
            }
        }
        
        // Try to calculate time difference between candles
        System.out.println("\nTime differences between consecutive candles:");
        for (int i = 1; i < ohlcData.size(); i++) {
            Duration duration = Duration.between(
                ohlcData.get(i-1).timestamp, 
                ohlcData.get(i).timestamp
            );
            System.out.printf("Between candle %d and %d: %d minutes%n", 
                i, i+1, duration.toMinutes());
        }
    }
    
    static class OHLC {
        ZonedDateTime timestamp;
        double open, high, low, close;
        
        OHLC(ZonedDateTime timestamp, double open, double high, double low, double close) {
            this.timestamp = timestamp;
            this.open = open;
            this.high = high;
            this.low = low;
            this.close = close;
        }
        
        @Override
        public String toString() {
            return String.format("%s - O:%.1f H:%.1f L:%.1f C:%.1f", 
                timestamp.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm z")),
                open, high, low, close);
        }
    }
}
```

**Comment by francescopeloi** [comment] 2024-10-10 10:24
ah! Finally I understand the problem I am having every start of October :smile:  Thanks for describing it so well.

**Comment by TheCookieLab** [comment] 2024-10-10 14:02
While it is an issue, it's not a bug. The gap and overlap are features that accurately reflect how DST works in the real world. There literally is a missing hour when springing forward and vice versa when falling back. Those working in lower time frames where DST is relevant would need to account for it in their code, again just like someone would when planning their schedule in the real world.

That said I've come around to the idea of moving to Instant. The transition would not be overly burdensome and in along with the arguments provided, it would help with certain scenarios in building lower time frame bar series around DST that currently have no easy workaround.

This discussion can continue in #1191 with the implementation details.

**Closed** 2024-10-11 21:18 UTC
Labels: enhancement
